export const PARAMETER_OPTIONS = [
  'Av. check',
  'Points',
  'Goods in check',
  'Promotion',
  'Loyalty card reg',
  'MAU',
  'DAU',
  'WAU',
  'Churn probability',
  'Retention probability',
  'Purchase probability',
  'Returned period',
  'Purchases per week',
  'Purchases per month',
  'Purchases per week',
  'Period',
  'Life time',
  'LTV',
  'City',
  'Region',
  'Country',
  'Mode',
  'Median',
  'Average',
  'Income',
  'Profit',
  'User status',
  'Segment',
  'Selection table',
  'Device',
  'Have app (yes, no)',
  'Loyalty card'
];

export const BONUS_OPTIONS = [
  'Gift 1',
  'Gift 2',
  'Gift 3',
  'Gift 4',
  'Gift 5'
];

export const PRODUCT_OPTIONS = [
  'Фрикадельки (домашний полуфабрикат)',
  'Котлеты (домашний полуфабрикат)',
  'Суповой набор куриный',
  'Суповой набор мясной',
  'Готовый мясной бульон',
  'Готовый куриный бульон',
  'Курица (бедра или окорочка)',
  'Куриное филе',
  'Свинина порционная по 300 г',
  'Сало',
  'Стручковая фасоль',
  'Маргарин',
  'Сливочное масло',
  'Ягоды (смородина, клубника, клюква и т.д.)',
  'Отварные грибы',
  'Шпинат',
  'Слоеное тесто',
  'Рыба (любая)',
  'Крабовые палочки',
];