import Chart1 from './images/chart1.png';
import Chart2 from './images/chart2.png';
import Chart3 from './images/chart3.png';
import ReportHeader from "../../components/ReportHeader";

const ReportCommon = () => {

  return (
    <div className='form-page'>
      <h2 className='form-page__description'>Данные по отчету - общие данные</h2>
      <div className='form-page__content form-page__content-report'>
        <ReportHeader/>
        <div className='chart-wrapper'>
          <img src={Chart1} alt="chart"/>
          <img src={Chart2} alt="chart"/>
          <img src={Chart3} alt="chart"/>
        </div>
        <div className='report-box common-report'>
          <p className='middle-title-cell'>Месяц</p>
          <p className='middle-title-cell'>Дата начала</p>
          <p className='middle-title-cell'>Дата окончания</p>
          <p className='middle-title-cell'>Название компании</p>
          <p className='middle-title-cell'>Канал коммуникации</p>
          <p className='middle-title-cell'>Выборка</p>
          <p className='middle-title-cell'>Отправлено, шт</p>
          <p className='middle-title-cell'>Доставлено, шт</p>
          <p className='middle-title-cell'>OR, %</p>
          <p className='middle-title-cell'>CR, %</p>
          <p className='middle-title-cell'>Открыли, чел</p>
          <p className='middle-title-cell'>Перешли/чел</p>
          <p className='middle-title-cell'>Перешли/клики</p>
          <p className='middle-title-cell'>CTOR, %</p>
          <p className='middle-title-cell'>Ср. чек заказы email, руб</p>
          <p className='middle-title-cell'>Заказы, шт</p>
          <p className='middle-title-cell'>Конверсия, %</p>
          <p className='middle-title-cell'>Выручка по заказам, руб</p>

          <p className='text-cell bg-light'>Февраль</p>
          <p className='text-cell bg-dark'>17.02.2021</p>
          <p className='text-cell bg-light'>24.02.2021</p>
          <p className='text-cell bg-dark'>Скидка 23% - на продукты из списка</p>
          <p className='text-cell bg-light'>Push app</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>374 550</p>
          <p className='text-cell bg-dark'>280 913</p>
          <p className='text-cell bg-light'>33,57%</p>
          <p className='text-cell bg-dark'>0,06%</p>
          <p className='text-cell bg-light'>56 183</p>
          <p className='text-cell bg-dark'>41013</p>
          <p className='text-cell bg-light'>8 203</p>
          <p className='text-cell bg-dark'>6,83%</p>
          <p className='text-cell bg-light'>2 261</p>
          <p className='text-cell bg-dark'>226</p>
          <p className='text-cell bg-light'>0,05%</p>
          <p className='text-cell bg-dark'>376 414</p>

          <p className='text-cell'>Февраль</p>
          <p className='text-cell bg-light'>17.02.2021</p>
          <p className='text-cell'>24.02.2021</p>
          <p className='text-cell bg-light'>Скидка 23% - на продукты из списка</p>
          <p className='text-cell'>SMS</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>419 2750</p>
          <p className='text-cell bg-light'>314 456</p>
          <p className='text-cell'>12,54%</p>
          <p className='text-cell bg-light'>0,47%</p>
          <p className='text-cell'>62 891</p>
          <p className='text-cell bg-light'>45911</p>
          <p className='text-cell'>9 182</p>
          <p className='text-cell bg-light'>9,48%</p>
          <p className='text-cell'>2 242</p>
          <p className='text-cell bg-light'>224</p>
          <p className='text-cell'>0,44%</p>
          <p className='text-cell bg-light'>645 652</p>

          <p className='text-cell bg-light'>Февраль</p>
          <p className='text-cell bg-dark'>19.02.2021</p>
          <p className='text-cell bg-light'>28.02.2021</p>
          <p className='text-cell bg-dark'>Молоко и Йогурт в 2x больше балловв</p>
          <p className='text-cell bg-light'>Push app</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>480 732</p>
          <p className='text-cell bg-dark'>360 549</p>
          <p className='text-cell bg-light'>12,33%</p>
          <p className='text-cell bg-dark'>0,54%</p>
          <p className='text-cell bg-light'>72 110</p>
          <p className='text-cell bg-dark'>52640</p>
          <p className='text-cell bg-light'>10 528</p>
          <p className='text-cell bg-dark'>11,79%</p>
          <p className='text-cell bg-light'>2 769</p>
          <p className='text-cell bg-dark'>277</p>
          <p className='text-cell bg-light'>0,82%</p>
          <p className='text-cell bg-dark'>573 054</p>

          <p className='text-cell'>Февраль</p>
          <p className='text-cell bg-light'>21.02.2021</p>
          <p className='text-cell'>24.02.2021</p>
          <p className='text-cell bg-light'>15 фото Премиум в подарок</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>479 137</p>
          <p className='text-cell bg-light'>359 353</p>
          <p className='text-cell'>15,11%</p>
          <p className='text-cell bg-light'>0,76%</p>
          <p className='text-cell'>71 871</p>
          <p className='text-cell bg-light'>52466</p>
          <p className='text-cell'>10 493</p>
          <p className='text-cell bg-light'>5,36%</p>
          <p className='text-cell'>2 801</p>
          <p className='text-cell bg-light'>280</p>
          <p className='text-cell'>0,98%</p>
          <p className='text-cell bg-light'>718 886</p>

          <p className='text-cell bg-light'>Февраль</p>
          <p className='text-cell bg-dark'>25.02.2021</p>
          <p className='text-cell bg-light'>28.02.2021</p>
          <p className='text-cell bg-dark'>Минибук в подарок, Скидка 25%</p>
          <p className='text-cell bg-light'>Push app</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>534 377</p>
          <p className='text-cell bg-dark'>400 783</p>
          <p className='text-cell bg-light'>22,43%</p>
          <p className='text-cell bg-dark'>0,50%</p>
          <p className='text-cell bg-light'>80 157</p>
          <p className='text-cell bg-dark'>58514</p>
          <p className='text-cell bg-light'>11 703</p>
          <p className='text-cell bg-dark'>11,53%</p>
          <p className='text-cell bg-light'>1 483</p>
          <p className='text-cell bg-dark'>148</p>
          <p className='text-cell bg-light'>0,70%</p>
          <p className='text-cell bg-dark'>687 998</p>

          <p className='text-cell'>Февраль</p>
          <p className='text-cell bg-light'>26.02.2021</p>
          <p className='text-cell'>02.03.2021</p>
          <p className='text-cell bg-light'>Скидка 20 %</p>
          <p className='text-cell'>E-mail</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>473 885</p>
          <p className='text-cell bg-light'>355 414</p>
          <p className='text-cell'>3,49%</p>
          <p className='text-cell bg-light'>0,56%</p>
          <p className='text-cell'>71 083</p>
          <p className='text-cell bg-light'>51890</p>
          <p className='text-cell'>10 378</p>
          <p className='text-cell bg-light'>7,84%</p>
          <p className='text-cell'>2 630</p>
          <p className='text-cell bg-light'>263</p>
          <p className='text-cell'>0,65%</p>
          <p className='text-cell bg-light'>654 285</p>

          <p className='text-cell bg-light'>Февраль</p>
          <p className='text-cell bg-dark'>28.02.2021</p>
          <p className='text-cell bg-light'>02.03.2021</p>
          <p className='text-cell bg-dark'>Оформи карту лояльностии покупай соскидкой 5%</p>
          <p className='text-cell bg-light'>E-mail</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>477 555</p>
          <p className='text-cell bg-dark'>358 166</p>
          <p className='text-cell bg-light'>0,54%</p>
          <p className='text-cell bg-dark'>0,77%</p>
          <p className='text-cell bg-light'>71 633</p>
          <p className='text-cell bg-dark'>52292</p>
          <p className='text-cell bg-light'>10 458</p>
          <p className='text-cell bg-dark'>11,05%</p>
          <p className='text-cell bg-light'>2 215</p>
          <p className='text-cell bg-dark'>222</p>
          <p className='text-cell bg-light'>0,33%</p>
          <p className='text-cell bg-dark'>501 449</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>02.03.2021</p>
          <p className='text-cell'>06.03.2021</p>
          <p className='text-cell bg-light'>Ваши любиме продукты</p>
          <p className='text-cell'>E-mail</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>260 000</p>
          <p className='text-cell bg-light'>195 000</p>
          <p className='text-cell'>11,00%</p>
          <p className='text-cell bg-light'>0,71%</p>
          <p className='text-cell'>39 000</p>
          <p className='text-cell bg-light'>28470</p>
          <p className='text-cell'>5 694</p>
          <p className='text-cell bg-light'>12,51%</p>
          <p className='text-cell'>3 185</p>
          <p className='text-cell bg-light'>319</p>
          <p className='text-cell'>0,38%</p>
          <p className='text-cell bg-light'>635 427</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>04.03.2021</p>
          <p className='text-cell bg-light'>10.03.2021</p>
          <p className='text-cell bg-dark'>Фото в сети за скидку</p>
          <p className='text-cell bg-light'>E-mail</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>371 955</p>
          <p className='text-cell bg-dark'>278 966</p>
          <p className='text-cell bg-light'>13,23%</p>
          <p className='text-cell bg-dark'>0,67%</p>
          <p className='text-cell bg-light'>55 793</p>
          <p className='text-cell bg-dark'>40729</p>
          <p className='text-cell bg-light'>8 146</p>
          <p className='text-cell bg-dark'>8,11%</p>
          <p className='text-cell bg-light'>1 864</p>
          <p className='text-cell bg-dark'>186</p>
          <p className='text-cell bg-light'>0,86%</p>
          <p className='text-cell bg-dark'>721 301</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>06.03.2021</p>
          <p className='text-cell'>10.03.2021</p>
          <p className='text-cell bg-light'>Топ-3 спортивных костюма😍 Промокод на скидку внутри</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>288 691</p>
          <p className='text-cell bg-light'>216 518</p>
          <p className='text-cell'>3,40%</p>
          <p className='text-cell bg-light'>0,57%</p>
          <p className='text-cell'>43 304</p>
          <p className='text-cell bg-light'>31612</p>
          <p className='text-cell'>6 322</p>
          <p className='text-cell bg-light'>5,91%</p>
          <p className='text-cell'>2 178</p>
          <p className='text-cell bg-light'>218</p>
          <p className='text-cell'>0,37%</p>
          <p className='text-cell bg-light'>593 606</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>10.03.2021</p>
          <p className='text-cell bg-light'>11.03.2021</p>
          <p className='text-cell bg-dark'>Батончик Марс со скидкой 30% только 3 дня</p>
          <p className='text-cell bg-light'>Push app</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>314 170</p>
          <p className='text-cell bg-dark'>235 628</p>
          <p className='text-cell bg-light'>11,81%</p>
          <p className='text-cell bg-dark'>0,38%</p>
          <p className='text-cell bg-light'>47 126</p>
          <p className='text-cell bg-dark'>34402</p>
          <p className='text-cell bg-light'>6 880</p>
          <p className='text-cell bg-dark'>5,72%</p>
          <p className='text-cell bg-light'>2 643</p>
          <p className='text-cell bg-dark'>264</p>
          <p className='text-cell bg-light'>0,60%</p>
          <p className='text-cell bg-dark'>737 598</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>11.03.2021</p>
          <p className='text-cell'>13.03.2021</p>
          <p className='text-cell bg-light'>До 45% по вашим любимым товарам! ⚡ Промокод внутри письма ⚡</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>373 221</p>
          <p className='text-cell bg-light'>279 916</p>
          <p className='text-cell'>32,40%</p>
          <p className='text-cell bg-light'>0,07%</p>
          <p className='text-cell'>55 983</p>
          <p className='text-cell bg-light'>40868</p>
          <p className='text-cell'>8 174</p>
          <p className='text-cell bg-light'>12,32%</p>
          <p className='text-cell'>2 903</p>
          <p className='text-cell bg-light'>290</p>
          <p className='text-cell'>0,93%</p>
          <p className='text-cell bg-light'>725 192</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>13.03.2021</p>
          <p className='text-cell bg-light'>16.03.2021</p>
          <p className='text-cell bg-dark'>Скидка 25% на все фотокниги✨Только 3 дня</p>
          <p className='text-cell bg-light'>SMS</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>253 048</p>
          <p className='text-cell bg-dark'>189 786</p>
          <p className='text-cell bg-light'>5,51%</p>
          <p className='text-cell bg-dark'>0,79%</p>
          <p className='text-cell bg-light'>37 957</p>
          <p className='text-cell bg-dark'>27709</p>
          <p className='text-cell bg-light'>5 542</p>
          <p className='text-cell bg-dark'>10,09%</p>
          <p className='text-cell bg-light'>2 246</p>
          <p className='text-cell bg-dark'>225</p>
          <p className='text-cell bg-light'>0,72%</p>
          <p className='text-cell bg-dark'>377 379</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>17.03.2021</p>
          <p className='text-cell'>22.03.2021</p>
          <p className='text-cell bg-light'>Всего 4 дня! оформи доставку без минимальной цены</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база, часть 1</p>
          <p className='text-cell'>443 391</p>
          <p className='text-cell bg-light'>332 543</p>
          <p className='text-cell'>11,14%</p>
          <p className='text-cell bg-light'>0,88%</p>
          <p className='text-cell'>66 509</p>
          <p className='text-cell bg-light'>48551</p>
          <p className='text-cell'>9 710</p>
          <p className='text-cell bg-light'>11,20%</p>
          <p className='text-cell'>2 079</p>
          <p className='text-cell bg-light'>208</p>
          <p className='text-cell'>0,89%</p>
          <p className='text-cell bg-light'>477 946</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>17.03.2021</p>
          <p className='text-cell bg-light'>23.03.2021</p>
          <p className='text-cell bg-dark'>Вооооу! Скидка до 30% на колбасы </p>
          <p className='text-cell bg-light'>Push app</p>
          <p className='text-cell bg-dark'>вся активная база, часть 2</p>
          <p className='text-cell bg-light'>401 437</p>
          <p className='text-cell bg-dark'>301 078</p>
          <p className='text-cell bg-light'>11,44%</p>
          <p className='text-cell bg-dark'>0,16%</p>
          <p className='text-cell bg-light'>60 216</p>
          <p className='text-cell bg-dark'>43957</p>
          <p className='text-cell bg-light'>8 791</p>
          <p className='text-cell bg-dark'>10,71%</p>
          <p className='text-cell bg-light'>2 234</p>
          <p className='text-cell bg-dark'>223</p>
          <p className='text-cell bg-light'>0,67%</p>
          <p className='text-cell bg-dark'>702 896</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>18.03.2021</p>
          <p className='text-cell'>24.03.2021</p>
          <p className='text-cell bg-light'>Вооооу! Надо успеть купить - до 50% скидка на пастельное белье</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>404 359</p>
          <p className='text-cell bg-light'>303 269</p>
          <p className='text-cell'>15,44%</p>
          <p className='text-cell bg-light'>0,56%</p>
          <p className='text-cell'>60 654</p>
          <p className='text-cell bg-light'>44277</p>
          <p className='text-cell'>8 855</p>
          <p className='text-cell bg-light'>11,94%</p>
          <p className='text-cell'>3 070</p>
          <p className='text-cell bg-light'>307</p>
          <p className='text-cell'>0,67%</p>
          <p className='text-cell bg-light'>475 663</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>18.03.2021</p>
          <p className='text-cell bg-light'>31.03.2021</p>
          <p className='text-cell bg-dark'>Скидка специально для вас💜 -45%  на товары для дома</p>
          <p className='text-cell bg-light'>SMS</p>
          <p className='text-cell bg-dark'></p>
          <p className='text-cell bg-light'>359 839</p>
          <p className='text-cell bg-dark'>269 879</p>
          <p className='text-cell bg-light'>23,30%</p>
          <p className='text-cell bg-dark'>0,28%</p>
          <p className='text-cell bg-light'>53 976</p>
          <p className='text-cell bg-dark'>39402</p>
          <p className='text-cell bg-light'>7 880</p>
          <p className='text-cell bg-dark'>9%</p>
          <p className='text-cell bg-light'>1 921</p>
          <p className='text-cell bg-dark'>192</p>
          <p className='text-cell bg-light'>0,98%</p>
          <p className='text-cell bg-dark'>554 952</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>18.03.2021</p>
          <p className='text-cell'>бессрочно</p>
          <p className='text-cell bg-light'>Заказывай продукты с доставкой 😷</p>
          <p className='text-cell'>SMS</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>370 387</p>
          <p className='text-cell bg-light'>277 790</p>
          <p className='text-cell'>15,44%</p>
          <p className='text-cell bg-light'>0,66%</p>
          <p className='text-cell'>55 558</p>
          <p className='text-cell bg-light'>40557</p>
          <p className='text-cell'>8 111</p>
          <p className='text-cell bg-light'>6,99%</p>
          <p className='text-cell'>2 016</p>
          <p className='text-cell bg-light'>202</p>
          <p className='text-cell'>0,03%</p>
          <p className='text-cell bg-light'>450 020</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>20.03.2021</p>
          <p className='text-cell bg-light'>22.03.2021</p>
          <p className='text-cell bg-dark'>Дарим к вашему чеку подарки, собирай стикеры и получай подарки 😄</p>
          <p className='text-cell bg-light'>SMS</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>342 707</p>
          <p className='text-cell bg-dark'>257 030</p>
          <p className='text-cell bg-light'>13,45%</p>
          <p className='text-cell bg-dark'>0,05%</p>
          <p className='text-cell bg-light'>51 406</p>
          <p className='text-cell bg-dark'>37526</p>
          <p className='text-cell bg-light'>7 505</p>
          <p className='text-cell bg-dark'>5,31%</p>
          <p className='text-cell bg-light'>2 390</p>
          <p className='text-cell bg-dark'>239</p>
          <p className='text-cell bg-light'>0,08%</p>
          <p className='text-cell bg-dark'>709 925</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>21.03.2021</p>
          <p className='text-cell'>бессрочно</p>
          <p className='text-cell bg-light'>Как круто повести время с ребенком дома👶🤓😄</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>268 953</p>
          <p className='text-cell bg-light'>201 715</p>
          <p className='text-cell'>42,45%</p>
          <p className='text-cell bg-light'>0,36%</p>
          <p className='text-cell'>40 343</p>
          <p className='text-cell bg-light'>29450</p>
          <p className='text-cell'>5 890</p>
          <p className='text-cell bg-light'>12,99%</p>
          <p className='text-cell'>2 773</p>
          <p className='text-cell bg-light'>277</p>
          <p className='text-cell'>0,59%</p>
          <p className='text-cell bg-light'>432 903</p>

          <p className='text-cell bg-light'>Март</p>
          <p className='text-cell bg-dark'>23.03.2021</p>
          <p className='text-cell bg-light'>31.03.2021</p>
          <p className='text-cell bg-dark'>Скидки до 40% 🤩 Супер Ликвидация!🤩</p>
          <p className='text-cell bg-light'>Push app</p>
          <p className='text-cell bg-dark'>вся активная база</p>
          <p className='text-cell bg-light'>362 514</p>
          <p className='text-cell bg-dark'>271 886</p>
          <p className='text-cell bg-light'>15,44%</p>
          <p className='text-cell bg-dark'>0,05%</p>
          <p className='text-cell bg-light'>54 377</p>
          <p className='text-cell bg-dark'>39695</p>
          <p className='text-cell bg-light'>7 939</p>
          <p className='text-cell bg-dark'>6,48%</p>
          <p className='text-cell bg-light'>3 182</p>
          <p className='text-cell bg-dark'>318</p>
          <p className='text-cell bg-light'>0,37%</p>
          <p className='text-cell bg-dark'>595 753</p>

          <p className='text-cell'>Март</p>
          <p className='text-cell bg-light'>25.03.2021</p>
          <p className='text-cell'>27.03.2021</p>
          <p className='text-cell bg-light'>Готовые наборы с вашими продуктми - заказывай каждую неделю и увеличвай скидку</p>
          <p className='text-cell'>Push app</p>
          <p className='text-cell bg-light'>вся активная база</p>
          <p className='text-cell'>489 885</p>
          <p className='text-cell bg-light'>489 885</p>
          <p className='text-cell'>14,44%</p>
          <p className='text-cell bg-light'>0,79%</p>
          <p className='text-cell'>73 483</p>
          <p className='text-cell bg-light'>53642</p>
          <p className='text-cell'>10 728</p>
          <p className='text-cell bg-light'>11,07%</p>
          <p className='text-cell'>2 307</p>
          <p className='text-cell bg-light'>231</p>
          <p className='text-cell'>0,89%</p>
          <p className='text-cell bg-light'>616 599</p>
        </div>
      </div>
    </div>
  )
}

export default ReportCommon;